version: '3.8'

services:
  nginx-unit:
    image: alicekaeva/collaborative_learning:latest
    platform: linux/amd64
    restart: always
    build:
      context: .
      target: stateless
      args:
        APP_ENV: prod
    environment:
      APP_ENV: prod
      DATABASE_URL: "mysql://user:password@mysql:3306/collaborative_learning?serverVersion=8.0.31&charset=utf8mb4"
    ports:
      - "127.0.0.1:9999:8080"

  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "collaborative_learning"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  ###> doctrine/doctrine-bundle ###
  mysql-data:
  ###< doctrine/doctrine-bundle ###
