controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_get_tags:
    path: '/get_tags/{categoryId}'
    controller: App\Controller\TagController::getTags
    methods: ['GET']
